### ISSUE TITLE
dance editor radio buttons submit form on enter

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#274]
When entering a dance using the figure editor, from keyboard position

-when I hit `enter`, I *want* the selected radiobutton or checkbox to be selected
-when I hit `enter`, right now the dance is saved prematurely with most figures left as 'empty figure'.

**Comment by dcmorse** [comment]
This is vexing me. Revising to a [4] because it appears I'll have to re-learn angular-js rather than cherry-picking the solution out of stack overflow. Please reprioritize accordingly. 

###  workaround
select radios from the keyboard using the spacebar. 


### notes to self
I can suppress the enter key on radios entirely, thereby making return not submit the form and also not select the radio item using [this technique](https://stackoverflow.com/a/45763640/5158597). That seems pretty worthless. From

**Comment by dcmorse** [comment]
@cranhandler motion to close because of the [spacebar] workaround?

**Comment by cranhandler** [comment]
Success

Pardon brevity; sent by smartphone.
