### ISSUE TITLE
advanced figure search duplicate figures

### ISSUE THREAD

**Issue by cranhandler** [contradb/contra#360]
This question to Shared Weight looked like a perfect use for ContraDB.com's advanced figure search. 

```
Hey folks,

For REASONS, I'm in search of dances with more than one partner swing --
preferably one of which is a balance and swing. Thoughts?
```

Unfortunately, searching this combination: 
![image](https://user-images.githubusercontent.com/16180173/39493516-c44f86bc-4d58-11e8-9980-0c0e2f2016ac.png)

Returned 101 entries---which is actually the same search result return as if we searched dances with balance & swing alone. 

![image](https://user-images.githubusercontent.com/16180173/39493526-cfbbbb1a-4d58-11e8-9327-abfe027c8410.png)

Do we intend to support searching for separate instances of the same figure using the 'and' operator?

**Comment by dcmorse** [comment]
A "count" input on figure makes the most sense to me.

**Comment by dcmorse** [comment]
Well, it hasn't been implemented yet, but imagine when you open the accordion for a figure, in addition to all the other things, at the bottom there's a number text input labeled "repeats". It defaults to 1, but you can bump it up to, say, 4. Or bump it down to 0, I suppose, which would be equivalent to searching for "no figure". 


The reason counting based on 'and' will be a headache to implement is if the two arguments to `and` are different: things get tricky. Suppose under that scheme we searched for a dance with a swing, and a partner swing. Then consider coming on a dance with first a partner swing then a neighbor swing. First we'd probably try to satisfy by matching the first swings, and then discover that we couldn't reconcile the neighbor swing with the partner swing query, so then we'd have to backtrack, try to match the neighbor swing with the generic swing, and then match the partner swing with the partner swing. It gets very number-crunchy and computationally expensive in the general case with lots of arguments to and. So it's better to think of the `and` operator as a set membership query.

**Comment by cranhandler** [comment]
Reopening because 'Search' label replaces https://github.com/contradb/contra/issues/411

**Comment by dcmorse** [comment]
I now also don't like having a 'count' in the figure accordion.

It's fine in isolation, but it doesn't stack well in thens:

*(swing) then (chain, count 2)* - what does this even mean?

Hm.

**Comment by dcmorse** [comment]
# count to be added to the figure/and/or/then menu

Count runs its one subfilter and counts the number of matches (0 on nil), then compares it against the number (0,1,2,3,4,5,6,7,8) and the operator (>= <= > < == !=). It then either returns the same matches as the subfilter, or returns nil. If the subfilter itself returns nil, and the number/operator want a true result, we return the empty matching set. So that covers the case where they say `count 0 == contra corners`, that'll match any dance without a contra corners. 

## Upshot

if you ask for `swing then (count 2 <= promenade)` then you'll match dances that have two promenades, at least one of them right after a swing. This is slightly nonsense, but seems like the least nonsense idea I've got so far.
