### ISSUE TITLE
Replace welcome.js hackery with Angular

### ISSUE THREAD

**Issue by djpohly** [contradb/contra#454]
The search query builder code definitely isn't the cleanest shirt in the hamper - cobbling together strings of HTML with a bunch of JavaScript logic, then turning that whole DOM tree back into a JSON query is roundabout at best.  Fortunately, we already have Angular available in the project, which could do a lot of the heavy lifting for us, and in a more organized way.

Interested in having this code refactored into something a bit cleaner?

**Comment by dcmorse** [comment]
Thanks for the offer. I don't know. 

@cranhandler has recently made noises about redesigning the interface with UI lessons learned. Users aren't grasping prefix notation. Maybe it makes more sense to take part in the redesign and implementation of that?

Sidebar:

The lesson I came away from the whole experience of learning Angular 1 for the dance and program editors is: frameworks have a prohibitively high upkeep cost for relatively little benefit on small projects. I trained up in the framework, wrote the app, then 2 years later the app needs a rewrite because the framework is dying.

This mirrors my experience with Ember at work.  Lots of ramp up time, elegant code, poor extensibility, and the ramp-up time has to be repaid if one's not constantly working in that framework. 

Of course, as you observed, the code in welcome.js isn't a model of readability either. So far, though, I'm finding it less annoying to maintain. 

When I had to implement the back-button working correctly (or more correctly, anyway), I get the feeling I would have been out of luck had it been in Angular. And I also felt out-of-luck when it came to implementing hotkeys in the (Angluar-based) figure editor. 

So that's why the front page and the dialect editor are written in low-level jQuery instead of high-level framework de jour.

**Comment by djpohly** [comment]
Better any of the frameworks _du jour_ than the framework _du passé._  Your logic does make sense... if you assume a one-man development team indefinitely.  From the perspective of a person who didn't write the original, however, it took me longer to under how the current query builder works (at least well enough to fix some bugs) than to learn enough Angular to rewrite it.  Plus, the latter was a lot more fun.
